{"content": "In the code section 6.7, methodC is invalid.  Because methodA and methodB pass (or throw) exceptions, methodC must be prepared to handle them.  This can be handled in two ways: a try-catch block, which will handle the exception within the method and a throws clause which would in turn throw the exception to the caller to handle.  The above example will cause a compilation error, as Java is very strict about exception handling. So the programmer is forced to handle any possible error condition at some point.\n", "stemmed": "In code section 6.7 , methodc invalid . becaus methoda methodb pass ( throw ) except , methodc must prepar handl . thi handl two way : try-catch block , handl except within method throw claus would turn throw except caller handl . the exampl caus compil error , java strict except handl . So programm forc handl possibl error condit point .", "link": "https://en.wikibooks.org/wiki/Java_Programming/Throwing_and_Catching_Exceptions"}