{"content": "\nWhen an exception is caught, the exception contains the stack-trace, which describes the error and shows where the exception happened (i.e. where the problem is and where the application programmer should look to fix the problem). Sometimes it is desirable to catch an exception and throw another exception. If the new exception keeps a reference to the first exception, the first exception is called a nesting exception.\n", "stemmed": "when except caught , except contain stack-trac , describ error show except happen ( i.e . problem applic programm look fix problem ) . sometim desir catch except throw anoth except . If new except keep refer first except , first except call nest except .", "link": "https://en.wikibooks.org/wiki/Java_Programming/Nesting_Exceptions"}