{"content": "The above code is an example of a nesting exception. When the Exception is thrown, by passing in the ClassCastException object reference as a parameter, the ClassCastException is nested in the newly created Exception, its stack-trace is appended together. When the Exception is caught, its stack-trace contains the original ClassCastException's stack-trace.\n", "stemmed": "the code exampl nest except . when except thrown , pass classcastexcept object refer paramet , classcastexcept nest newli creat except , stack-trac append togeth . when except caught , stack-trac contain origin classcastexcept 's stack-trac .", "link": "https://en.wikibooks.org/wiki/Java_Programming/Nesting_Exceptions"}