{"content": "This conversion can also hide where the error is originated. The stack-trace starts when the exception is thrown. So when we catch and throw a new exception, the stack-trace starts at when the new exception was thrown, losing the original stack-trace. This was true with the earlier version of Java (before 1.4). Since then, so called cause facility capabilities were built in the Throwable class.\n", "stemmed": "thi convers also hide error origin . the stack-trac start except thrown . So catch throw new except , stack-trac start new except thrown , lose origin stack-trac . thi true earlier version java ( 1.4 ) . sinc , call caus facil capabl built throwabl class .", "link": "https://en.wikibooks.org/wiki/Java_Programming/Nesting_Exceptions"}